USE cofc2ajf;

CREATE TABLE IF NOT EXISTS FACULTY
(
	FID		CHAR(4) NOT NULL,
    LastName	VARCHAR(20) NOT NULL,
    FirstName	VARCHAR(20) NOT NULL,
    FacRank	CHAR(4),
    Tenured	CHAR(1),
    DeptID	CHAR(4),
    
    PRIMARY KEY (FID),
    FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DID)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
	STID		CHAR(8) NOT NULL,
    LastName	VARCHAR(20) NOT NULL,
    FirstName	VARCHAR(20) NOT NULL,
    Major	CHAR(4),
    Level	CHAR(2),
    GPA	DECIMAL(4,3),
    AdvisorID	CHAR(8),
    
    PRIMARY KEY (STID),
    FOREIGN KEY (AdvisorID) REFERENCES FACULTY(FID)
);

CREATE TABLE IF NOT EXISTS COURSE
(
	CID		CHAR(8) NOT NULL,
    Title	VARCHAR(80),
    DeptOffering	CHAR(4) NOT NULL,
    CreditHours INT,
    
    PRIMARY KEY (CID),
    FOREIGN KEY (DeptOffering) REFERENCES DEPARTMENT(DID)
);

CREATE TABLE IF NOT EXISTS SECTION
(
	SectID		CHAR(6) NOT NULL,
    CourseID	CHAR(8) NOT NULL,
    SectionNumber	CHAR(3) NOT NULL,
    Semester	CHAR(4) NOT NULL,
    Year	CHAR(4) NOT NULL,
    InstructorID	CHAR(8),
    
    PRIMARY KEY (SectID),
    FOREIGN KEY (CourseID) REFERENCES COURSE(CID),
    FOREIGN KEY (InstructorID) REFERENCES FACULTY(FID)
);

CREATE TABLE IF NOT EXISTS CLASS
(
	SectID		CHAR(6) NOT NULL,
    StudentID	CHAR(8) NOT NULL,
    Grade	CHAR(2),
    
    PRIMARY KEY (SectID, StudentID),
    FOREIGN KEY (SectID) REFERENCES SECTION(SectID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(STID)
);